config/routes.rb
Factpand3::Application.routes.draw do

  resource :reportes do
    get 'facturado', :on => :collection
    get 'movimientos', :on => :collection
    get 'articulos_reporte', :on => :collection
    get 'conjunto_articulos_reporte', :on => :collection
  end

  resources :notadedebitos do
    resources :renglon_notadebitos
    resources :renglon_ndddetalles
    resources :renglon_nddndcs
    resources :renglon_ndd_articulos
    get 'filtered' , :on => :collection
    get 'proximo_preimpreso', :on => :collection
    get 'generar_impresion' , :on => :collection
    get 'anular', :on => :collection
  end

  resources :notadecreditos do
    resources :renglon_notacreditos
    resources :renglon_ndcdetalles
    resources :renglon_ndcndds
    resources :renglon_ndc_articulos
    get 'filtered' , :on => :collection
    get 'proximo_preimpreso', :on => :collection
    get 'generar_impresion' , :on => :collection
    get 'anular', :on => :collection
  end

  resource :sessions, :only => [ :new, :create, :destroy]

  match '/signin', :to => 'sessions#new'

  match '/signout', :to => 'sessions#destroy'

  match '/signup', :to => 'users#new'

  resources :users

  resources :recibos do
    resources :renglon_recibos
    resources :renglon_recdetalles
    resources :renglon_recibo_docs
    get 'filtered' , :on => :collection
    get 'proximo_preimpreso', :on => :collection
    get 'generar_impresion' , :on => :collection
    get 'anular', :on => :collection
  end

  resources :facturas do
    get 'proximo_preimpreso', :on => :collection
    get 'filtered' , :on => :collection
    get 'generar_impresion' , :on => :collection
    get 'anular', :on => :collection
    resources :renglon_facturas
    resources :renglon_factdetalles
  end

  resources :listaprecios do
    get 'getPrecioArticuloCliente', :on => :collection
     get 'importarcliente', :on => :collection
    get 'copiarlista', :on => :collection
    resources :precioarts
  end

  root :to => "page#home"

  resources :articulocomps do
    resources :rolarticulos
    resources :comercializables do
      resources :precioarts
    end
  end

  resources :articuloinds do
    resources :rolarticulos
    resources :comercializables do
      resources :precioarts
    end
  end

  resources :tipoclientes do
    resources :mail_internos
  end

  resources :impuestos

  resources :pagocontados

  resources :pagoacreditos

  resources :monedas

  resources :formadepagos

  resources :articulos do
    resources :rolarticulos
    resources :comercializables do
      resources :precioarts
    end    
  end

  resources :promocions

  resources :sucursals

  resources :empresas do
    resources :contactos do
       resources :telefonos
       resources :mail_internos
    end
    resources :descuento_clientes
    resources :telefonos
    resources :mail_internos
    resources :sucursals do
      resources :telefonos
      resources :mail_internos
      resources :contactos do
        resources :telefonos
        resources :mail_internos
      end
    end
  end
  
  resources :sucursals do
    resources :telefonos
    resources :mail_internos
    resources :contactos do
      resources :telefonos
      resources :mail_internos
    end
  end

  resources :contactos do
    resources :telefonos
    resources :mail_internos
  end

  resources :clientes do
    resources :descuento_clientes
  end

  resources :personas do
    resources :telefonos
    resources :mail_internos
    resources :descuento_clientes
  end

end

app/models/renglon_recibo_doc.rb
# == Schema Information
#
# Table name: renglon_recibo_docs
#
#  id             :integer          not null, primary key
#  recibo_id      :integer          not null
#  documento_id   :integer          not null
#  documento_type :string(255)      not null
#  total_renglon  :float            not null
#  detalle        :string(255)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class RenglonReciboDoc < ActiveRecord::Base
  belongs_to :recibo
  belongs_to :documento, :polymorphic => true

  #attr_accessible :detalle, :documento_id, :documento_type, :total_impuestos, :total_renglon

  private


  validates :total_renglon, :presence => {:menssage => "Debe ingresar un Importe."}
  validate :saldo
  validate :documento_val
  validate :documento_impreso


  validates_numericality_of :total_renglon, :message => "El caracter de separacion decimal es .(Punto)."

  before_destroy :recibo_val?


  def documento_val

    if !self.documento.nil?
      if !self.id.nil?
        errors.add(:documento,"Ya existe un renglon con el mismo documento.") if self.recibo.renglon_recibo_docs.where("documento_id = ? and documento_type = ? and id <> ?" , self.documento.id.to_s, self.documento.class.name, self.id.to_s).size() > 0
      else
        errors.add(:documento,"Ya existe un renglon con el mismo documento.") if self.recibo.renglon_recibo_docs.where("documento_id = ? and documento_type = ? and id <> ?" , self.documento.id.to_s, self.documento.class.name, self.id.to_s).size() > 0
      end
    end

  end

  def recibo_val?
    errors.add(:recibo, "No puede modificar un Recibo impreso.") if self.recibo.impresa?
    errors.blank?
  end

  def saldo
    if !self.documento.nil?
      if self.documento.class.name == "Factura" || self.documento.class.name == "Notadedebito"
        errors.add(:total_linea,"No puede asignar un importe mayor al pendiente de la " + self.documento.class.name.to_s + " " + self.documento.id.to_s + ".") if self.documento.adeudo - (self.total_renglon )*self.recibo.moneda.tipodecambio/self.documento.moneda.tipodecambio < -1
      else
        errors.add(:total_linea,"No puede asignar un importe mayor al pendiente de la " + self.documento.class.name.to_s + " " + self.documento.id.to_s + ".") if self.documento.adeudo - (self.total_renglon )*self.recibo.moneda.tipodecambio/self.documento.moneda.tipodecambio > 1
      end
    end
  end

  def documento_impreso
    errors.add(:documento,"No puede asignar un documento que no fue Impresa.") if !self.documento.impresa?
  end

end

app/controllers/renglon_recibo_docs_controller.rb
class RenglonReciboDocsController < ApplicationController
  # GET /renglon_recibo_docs
  # GET /renglon_recibo_docs.json
  def index
    @recibo = Recibo.find(params[:recibo_id])
    @renglon_recibo_docs = @recibo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @renglon_recibo_docs }
    end
  end

  # GET /renglon_recibo_docs/1
  # GET /renglon_recibo_docs/1.json
  def show
    @recibo = Recibo.find(params[:recibo_id])
    @renglon_recibo_doc = @recibo.renglon_recibo_docs.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @renglon_recibo_doc }
    end
  end

  # GET /renglon_recibo_docs/new
  # GET /renglon_recibo_docs/new.json
  def new
    @renglon_recibo_doc = RenglonReciboDoc.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @renglon_recibo_doc }
    end
  end

  # GET /renglon_recibo_docs/1/edit
  def edit
    @recibo = Recibo.find(params[:recibo_id])
    @renglon_recibo_doc = @recibo.renglon_recibo_docs.find(params[:id])
    respond_to do |format|
      format.html { render :layout => 'special_form'}# new.html.erb
      format.json { render json: @renglon_recibo_doc }
    end
  end

  # POST /renglon_recibo_docs
  # POST /renglon_recibo_docs.json
  def create
    @recibo = Recibo.find(params[:recibo_id])
    @renglon_recibo_doc = @recibo.renglon_recibo_docs.build(params[:renglon_recibo_doc])

    respond_to do |format|
      if @renglon_recibo_doc.save
        #format.html { redirect_to @recibo, notice: 'Renglon recibo was successfully created.' }
        format.json { render json: @renglon_recibo_doc }
      else
        #format.html { render action: "new" }
        format.json { render json: @renglon_recibo_doc.errors }
      end
    end
  end

  # PUT /renglon_recibo_docs/1
  # PUT /renglon_recibo_docs/1.json
  def update
    @recibo = Recibo.find(params[:recibo_id])
    @renglon_recibo_doc = @recibo.renglon_recibo_docs.find(params[:id])

    respond_to do |format|
      if @renglon_recibo_doc.update_attributes(params[:renglon_recibo_doc])
        #format.html { redirect_to @recibo, notice: 'Renglon recibo was successfully updated.' }
        format.json { render json: @renglon_recibo_doc }
      else
        #format.html { render action: "edit" }
        format.json { render json: @renglon_recibo_doc.errors }
      end
    end
  end

  # DELETE /renglon_recibo_docs/1
  # DELETE /renglon_recibo_docs/1.json
  def destroy
    @recibo = Recibo.find(params[:recibo_id])
    respond_to do |format|
      if @renglon_recibo = @recibo.renglon_recibo_docs.find(params[:id]).destroy
        format.html { head :ok }
        format.json { head :ok }
      else
        format.html { head :ok }
        format.json { head :ok }
      end
    end
  end
end

app/helpers/renglon_recibo_docs_helper.rb
module RenglonReciboDocsHelper
end

app/views/renglon_recibo_docs/_form.html.erb
<%= @rand = "" %>

  <%  @rand = (0...8).map{65.+(rand(25)).chr}.join %>

<script>

  $(function() {

   


    $( "#guardar<%=@rand%>" ).button();
    $( "#guardar<%=@rand%>" ).click(function() {
      $(this).button( "disable" )
      var data = new Object();
<% if(@renglon_recibo_doc.id!=nil) %>
        data["_method"] =	"put";
<% end; %>
      data['renglon_recibo_doc[documento_id]']    =	$( "#documento_id<%=@rand%>" ).val();
      data['renglon_recibo_doc[documento_type]']  =	$( "#documento_type<%=@rand%>" ).val();
      data['renglon_recibo_doc[total_renglon]']   =	$( "#total_renglon<%=@rand%>" ).val();
      //data['renglon_recibo_doc[total_impuestos]'] =	$( "#total_impuestos<%=@rand%>" ).val();
      data['renglon_recibo_doc[detalle]']         =	$( "#detalle<%=@rand%>" ).val();
      data["utf8"] =	true;
      $.ajax({
        type: "POST",
        url: "/recibos/<%= @recibo.id %>/renglon_recibo_docs<% if (@renglon_recibo_doc==nil) %>.json<% else %>/<%= @renglon_recibo_doc.id %>.json<%end%>",
        data: data,
        context: document.body,
        success: function(json_data){
          $( "#guardar<%=@rand%>" ).button( "enable" )
          if (json_data.id){
            $("#texto_error").html("");
            tab_selected.click();
            <% if(@renglon_recibo_doc.id!=nil) %>
            reloadIframe("/recibos/<%=@renglon_recibo_doc.recibo_id %>/renglon_recibo_docs/<%=@renglon_recibo_doc.id%>/edit");
            <% end %>
             reloadIframe("/recibos/<%=@renglon_recibo_doc.recibo_id %>/edit");
          }else{
            $("#texto_error<%=@rand%>").html("");
            for (var i in json_data){
              var error = '<div style="padding: 0 .2em;" class="ui-state-error ui-corner-all"><p><span style="float: left; margin-right: .3em;" class="ui-icon ui-icon-alert"></span><strong>'+i+':</strong> '+json_data[i]+'.</p></div><br/>';
              $("#texto_error<%=@rand%>").html($("#texto_error").html()+error);

            }
          }

        },
        error: function( xhr, status, index, anchor ) {
          $( "#guardar<%=@rand%>" ).button( "enable" )
          $("#texto_error<%=@rand%>").html("");
          var error = '<div style="padding: 0 .2em;" class="ui-state-error ui-corner-all"><p><span style="float: left; margin-right: .3em;" class="ui-icon ui-icon-alert"></span><strong>0: </strong>Error interno.</p></div><br/>';
          $("#texto_error<%=@rand%>").html($("#texto_error").html()+error);

        
        }
      });
      return false;
    });

  });

</script>

<% if  (@renglon_recibo_doc==nil) %>
  <% @renglon_recibo_doc = RenglonReciboDoc.new %>
<% end %>

<%= form_for([@recibo,@renglon_recibo_doc]) do |f| %>
  <% if @renglon_recibo_doc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@renglon_recibo_doc.errors.count, "error") %> prohibited this renglon_recibo_doc from being saved:</h2>

      <ul>
      <% @renglon_recibo_doc.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  

  <div id ="texto_error<%=@rand%>"></div>
  <%= f.hidden_field :documento_id, :size =>20, :class =>  'text ui-widget-content ui-corner-all', :id => "documento_id"+@rand.to_s %>
  <%= f.hidden_field :documento_type, :size =>20, :class =>  'text ui-widget-content ui-corner-all',  :id => "documento_type"+@rand.to_s %>

  <div class="field">
    <%= f.label "Tipo de Documento" %><br />
     <div class ="combobox"><%= f.label @renglon_recibo_doc.documento_type %> </div>
  </div>
  <div class="field">
    <%= f.label :total_renglon %><br />
    <div class ="combobox"> <%= f.text_field :total_renglon, :size =>20, :class =>  'text ui-widget-content ui-corner-all', :id => "total_renglon"+@rand.to_s %></div>
  </div>
 
  <div class="field">
    <%= f.label :detalle %><br />
    <div class ="combobox"> <%= f.text_field :detalle , :size =>20, :class =>  'text ui-widget-content ui-corner-all', :id => "detalle"+@rand.to_s%></div>
  </div>
  <br/>
  <div class="actions" >
    <a id="guardar<%=@rand%>"><%if (@renglon_recibo_doc.id!=nil) %>Guardar Cambios <%else%>Crear Nuevo<%end%> </a>
  </div>
<% end %>

app/views/renglon_recibo_docs/_renglon_recibo_doc.html.erb
<tr>
  <th class="ui-state-default ui-corner-all" width="50px">  <%= renglon_recibo_doc.documento.numero %></th>
  <th class="ui-state-default ui-corner-all" width="50px">  <%=   if (renglon_recibo_doc.documento.class.name != "Notadecredito")
                                                                        renglon_recibo_doc.documento.class.name
                                                                  else
                                                                    (renglon_recibo_doc.documento.es_devolucion == true)?"Nota de Devolucion" : "Nota de Credito"
                                                                  end %></th>
  <th class="ui-state-default ui-corner-all" width="50px">  <%= ((renglon_recibo_doc.total_renglon)*100).round/100.0 %></th>
  <th  class="ui-state-default ui-corner-all"><a href ="#" data="/recibos/<%=renglon_recibo_doc.recibo.id%>/renglon_recibo_docs/<%=  renglon_recibo_doc.id %>/edit" dataw="600"  datah="600" class="edit_sub_link<%=@randa%>" title="Editar Linea"><span class="ui-icon ui-icon-wrench"></span></a></th>
  <th  class="ui-state-default ui-corner-all"><a href="#" action="/recibos/<%=renglon_recibo_doc.recibo.id%>/renglon_recibo_docs/<%=  renglon_recibo_doc.id %>" class="delete_sub_list<%=@randa%>" data-method="delete" title="Eliminar Linea"><span class="ui-icon ui-icon-trash"></span></a></th>
</tr>

app/views/renglon_recibo_docs/edit.html.erb
<%= render 'form' %>

app/views/renglon_recibo_docs/index.html.erb
<h1>Listing renglon_recibo_docs</h1>

<table>
  <tr>
    <th>Recibo</th>
    <th>Documento</th>
    <th>Documento type</th>
    <th>Total renglon</th>
    <th>Total impuestos</th>
    <th>Detalle</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @renglon_recibo_docs.each do |renglon_recibo_doc| %>
  <tr>
    <td><%= renglon_recibo_doc.recibo %></td>
    <td><%= renglon_recibo_doc.documento_id %></td>
    <td><%= renglon_recibo_doc.documento_type %></td>
    <td><%= renglon_recibo_doc.total_renglon %></td>
    <td><%= renglon_recibo_doc.total_impuestos %></td>
    <td><%= renglon_recibo_doc.detalle %></td>
    <td><%= link_to 'Show', renglon_recibo_doc %></td>
    <td><%= link_to 'Edit', edit_renglon_recibo_doc_path(renglon_recibo_doc) %></td>
    <td><%= link_to 'Destroy', renglon_recibo_doc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Renglon recibo doc', new_renglon_recibo_doc_path %>

app/views/renglon_recibo_docs/new.html.erb
<h1>New renglon_recibo_doc</h1>

<%= render 'form' %>

<%= link_to 'Back', renglon_recibo_docs_path %>

app/views/renglon_recibo_docs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Recibo:</b>
  <%= @renglon_recibo_doc.recibo %>
</p>

<p>
  <b>Documento:</b>
  <%= @renglon_recibo_doc.documento_id %>
</p>

<p>
  <b>Documento type:</b>
  <%= @renglon_recibo_doc.documento_type %>
</p>

<p>
  <b>Total renglon:</b>
  <%= @renglon_recibo_doc.total_renglon %>
</p>

<p>
  <b>Total impuestos:</b>
  <%= @renglon_recibo_doc.total_impuestos %>
</p>

<p>
  <b>Detalle:</b>
  <%= @renglon_recibo_doc.detalle %>
</p>


<%= link_to 'Edit', edit_renglon_recibo_doc_path(@renglon_recibo_doc) %> |
<%= link_to 'Back', renglon_recibo_docs_path %>