config/routes.rb
Factpand3::Application.routes.draw do

  resource :reportes do
    get 'facturado', :on => :collection
    get 'movimientos', :on => :collection
    get 'articulos_reporte', :on => :collection
    get 'conjunto_articulos_reporte', :on => :collection
  end

  resources :notadedebitos do
    resources :renglon_notadebitos
    resources :renglon_ndddetalles
    resources :renglon_nddndcs
    resources :renglon_ndd_articulos
    get 'filtered' , :on => :collection
    get 'proximo_preimpreso', :on => :collection
    get 'generar_impresion' , :on => :collection
    get 'anular', :on => :collection
  end

  resources :notadecreditos do
    resources :renglon_notacreditos
    resources :renglon_ndcdetalles
    resources :renglon_ndcndds
    resources :renglon_ndc_articulos
    get 'filtered' , :on => :collection
    get 'proximo_preimpreso', :on => :collection
    get 'generar_impresion' , :on => :collection
    get 'anular', :on => :collection
  end

  resource :sessions, :only => [ :new, :create, :destroy]

  match '/signin', :to => 'sessions#new'

  match '/signout', :to => 'sessions#destroy'

  match '/signup', :to => 'users#new'

  resources :users

  resources :recibos do
    resources :renglon_recibos
    resources :renglon_recdetalles
    resources :renglon_recibo_docs
    get 'filtered' , :on => :collection
    get 'proximo_preimpreso', :on => :collection
    get 'generar_impresion' , :on => :collection
    get 'anular', :on => :collection
  end

  resources :facturas do
    get 'proximo_preimpreso', :on => :collection
    get 'filtered' , :on => :collection
    get 'generar_impresion' , :on => :collection
    get 'anular', :on => :collection
    resources :renglon_facturas
    resources :renglon_factdetalles
  end

  resources :listaprecios do
    get 'getPrecioArticuloCliente', :on => :collection
     get 'importarcliente', :on => :collection
    get 'copiarlista', :on => :collection
    resources :precioarts
  end

  root :to => "page#home"

  resources :articulocomps do
    resources :rolarticulos
    resources :comercializables do
      resources :precioarts
    end
  end

  resources :articuloinds do
    resources :rolarticulos
    resources :comercializables do
      resources :precioarts
    end
  end

  resources :tipoclientes do
    resources :mail_internos
  end

  resources :impuestos

  resources :pagocontados

  resources :pagoacreditos

  resources :monedas

  resources :formadepagos

  resources :articulos do
    resources :rolarticulos
    resources :comercializables do
      resources :precioarts
    end    
  end

  resources :promocions

  resources :sucursals

  resources :empresas do
    resources :contactos do
       resources :telefonos
       resources :mail_internos
    end
    resources :descuento_clientes
    resources :telefonos
    resources :mail_internos
    resources :sucursals do
      resources :telefonos
      resources :mail_internos
      resources :contactos do
        resources :telefonos
        resources :mail_internos
      end
    end
  end
  
  resources :sucursals do
    resources :telefonos
    resources :mail_internos
    resources :contactos do
      resources :telefonos
      resources :mail_internos
    end
  end

  resources :contactos do
    resources :telefonos
    resources :mail_internos
  end

  resources :clientes do
    resources :descuento_clientes
  end

  resources :personas do
    resources :telefonos
    resources :mail_internos
    resources :descuento_clientes
  end

end

app/models/precioart.rb
# == Schema Information
#
# Table name: precioarts
#
#  id                 :integer          not null, primary key
#  precio             :float            default(0.0)
#  descuento          :float            default(0.0)
#  comercializable_id :integer          not null
#  listaprecio_id     :integer          not null
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#


class Precioart < ActiveRecord::Base

  belongs_to :comercializable
  belongs_to :listaprecio

  private


  validate :comercializable_val
  validates :comercializable_id, :presence => {:message => "Debe seleccionar un Articulo."}
  validates_numericality_of :descuento, :message => "El caracter de separacion decimal es .(Punto)."
  validates_numericality_of :precio, :message => "El caracter de separacion decimal es .(Punto)."


  def comercializable_val
    if self.comercializable
      for pr in self.listaprecio.precioarts
        errors.add(:comercializable,"Ya existe el articulo en la lista") if pr.comercializable.id == self.comercializable.id  and self.id != pr.id
      end
    end
  end

end

app/controllers/precioarts_controller.rb
class PrecioartsController < ApplicationController

  before_filter :authenticate

  # GET /precioarts
  # GET /precioarts.json
  def index
    @listaprecio = Listaprecio.find(params[:listaprecio_id])
    @precioarts = @listaprecio.precioarts

    respond_to do |format|
      format.html # index.html.erb
      #format.json { render json: @precioarts }
    end
  end

  # GET /precioarts/1
  # GET /precioarts/1.json
  def show
    @listaprecio = Listaprecio.find(params[:listaprecio_id])
    @precioarts = @listaprecio.precioarts.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      #format.json { render json: @precioart }
    end
  end

  # GET /precioarts/new
  # GET /precioarts/new.json
  def new
    @precioart = Precioart.new

    respond_to do |format|
      format.html { render :layout => 'special_form'}# new.html.erb
     #format.json { render json: @precioart }
    end
  end

  # GET /precioarts/1/edit
  def edit
    @listaprecio = Listaprecio.find(params[:listaprecio_id])
    @precioarts = @listaprecio.precioarts.find(params[:id])
    respond_to do |format|
      format.html { render :layout => 'special_form'}# new.html.erb
      #format.json { render json: @precioarts }
    end
  end

  # POST /precioarts
  # POST /precioarts.json
  def create
    @listaprecio = Listaprecio.find(params[:listaprecio_id])
    @precioarts = @listaprecio.precioarts.create(params[:precioart])

    respond_to do |format|
      if @precioarts.save
        format.html { redirect_to edit_listaprecio_path(@listaprecio), :notice => 'Precioart was successfully created.' }
        format.json { render json: @precioarts }
      else
        format.html { render :action => "new" }
        format.json { render json: @precioarts.errors }
      end
    end
  end

  # PUT /precioarts/1
  # PUT /precioarts/1.json
  def update
    @listaprecio = Listaprecio.find(params[:listaprecio_id])
    @precioarts = @listaprecio.precioarts.find(params[:id])
    
    respond_to do |format|
      if @precioarts.update_attributes(params[:precioart])
        if (params[:com].to_s == "true")
            format.html { redirect_to @precioarts, :notice => 'Precioart was successfully.' }
            format.json { render json: @precioart }
        else
           format.html { redirect_to edit_listaprecio_path(@listaprecio), :notice => 'Precioart was successfully updated.' }
           format.json { render json: @listaprecio }
        end        
        
      else
        format.html { render :action => "edit" }
        format.json { render json: @precioarts.errors}
      end
    end
  end

  # DELETE /precioarts/1
  # DELETE /precioarts/1.json
  def destroy
    @listaprecio = Listaprecio.find(params[:listaprecio_id])
    @precioarts = @listaprecio.precioarts.find(params[:id]).destroy

    respond_to do |format|
      format.html { redirect_to edit_listaprecio_path(@listaprecio)}
      #format.json { head :ok }
    end
  end
  
 end

app/helpers/precioarts_helper.rb
module PrecioartsHelper
end

app/views/precioarts/_editcom.html.erb
<%= form_for([@lp,@precioart]) do |f| %>
  <% if @lp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lp.errors.count, "error") %> prohibited this precioart from being saved:</h2>

      <ul>
      <% @lp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :precio %>
    <%= f.text_field :precio %>
    <%= f.label :descuento %>
    <%= f.text_field :descuento %>

  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/precioarts/_form.html.erb
<script>
<%

@rand = "";
if (@precioarts!=nil)
  @rand = @precioarts.id

end

%>
  var renglon_lista_comercializable_id<%= @rand %> = <%if (!@precioarts.nil?) %><%=  @precioarts.comercializable.id  %><%else%>-1<%end;%>;
  $(function() {

    $( "#guardar_precioart<%= @rand %>" ).button();
    $( "#guardar_precioart<%= @rand %>" ).click(function() {
      $( "#guardar_precioart<%= @rand %>" ).button("disable");
      var data = new Object();
<% if( @precioarts!=nil) %>
        data["_method"] =	"put";
<% end; %>
      data["precioart[precio]"] =	$( "#precioart_precio<%= @rand %>" ).val();
      data["precioart[descuento]"] =	$( "#precioart_descuento<%= @rand %>" ).val();
      data["precioart[comercializable_id]"] =	renglon_lista_comercializable_id<%= @rand %>;


      data['commit'] = "Update Listaprecios"
      data["utf8"] =	true;
      $.ajax({
        type: "POST",
        url: "/listaprecios/<%= @listaprecio.id %>/precioarts<% if (@precioarts ==nil) %>.json/ <% else %>/<%= @precioarts.id %>.json <%end%>",
        data: data,
        context: document.body,
        success: function(json_data){
          $( "#guardar_precioart<%= @rand %>" ).button( "enable" )
          if (json_data.id){
              
<% if( @precioarts!=nil) %>
              closeIframe("/listaprecios/<%=@listaprecio.id%>/precioarts/<%=@precioarts.id %>/edit");
<% end;%>
            reloadIframe("/listaprecios/<%=@listaprecio.id%>/edit");
          }else{
            $("#ineer_error<%= @rand %>").html("");
            for (var i in json_data){
              var error = '<div style="padding: 0 .2em;" class="ui-state-error ui-corner-all"><p><span style="float: left; margin-right: .3em;" class="ui-icon ui-icon-alert"></span><strong>'+i+':</strong> '+json_data[i]+'.</p></div><br/>';
              $("#ineer_error<%= @rand %>").html($("#ineer_error<%= @rand %>").html()+error);

            }
          }
        },
        error: function( xhr, status, index, anchor ) {
          $( "#guardar_precioart<%= @rand %>" ).button( "enable" )
          $("#ineer_error<%= @rand %>").html("");
          
            var error = '<div style="padding: 0 .2em;" class="ui-state-error ui-corner-all"><p><span style="float: left; margin-right: .3em;" class="ui-icon ui-icon-alert"></span><strong>Error:</strong>Error inerno.</p></div><br/>';
            $("#ineer_error<%= @rand %>").html($("#ineer_error<%= @rand %>").html()+error);

          
        }
      });
      return false;
    });
  });
   $( "#comercializable_id<%= @rand %>" ).autocomplete({
      source: function( request, response ) {
         var search = request.term;
        if(request.term == "no search")
          search = "";
        var url = "/articuloinds.json?comercializable="+search;
        $.ajax({
          url: url,
          success: function( data ) {

            if(data.length == 0){
              data = [{
                  id :-1,
                  texto: "no se encontraron resultados"
                }];
            }
            response( $.map( data, function( item ) {
              if (item.id == -1){
                return {
                  label: "no se encotraron resultados" ,
                  value: request.term,
                  id :item.id
                }
              }else{
                return {
                  label: item.nombre + " (" + item.id + ")" ,
                  value:  item.nombre ,
                  id :item.id,
                  complete_data : item
                }
              }
            })
          );
          },
          error: function( xhr, status, index, anchor ) {
            return {
              label: 'no se econtro reultado' ,
              value: request.term,
              id :-1
            }
          }
        });
      },
      minLength: 1,
      select: function( event, ui ) {

        if(ui.item.id != -1){
          renglon_lista_comercializable_id<%= @rand %> = ui.item.complete_data.id;
         // cargarDatos(ui.item.complete_data.id);
          $("#nombre_producto<%= @rand %>").html(ui.item.label  );
        }
        // showIframe("/articuloinds/"+ui.item.id+"/edit","Editar Articulo",500,500);
      },
      open: function() {
        $( this ).removeClass( "ui-corner-all" ).addClass( "ui-corner-top" );
      },
      close: function() {
        $( this ).removeClass( "ui-corner-top" ).addClass( "ui-corner-all" );
      }
    });

</script>

<% if  (@precioarts==nil) %>
  <% @precioarts = Precioart.new %>
<% end %>
<%= form_for([@listaprecio,@precioarts]) do |f| %>
  <% if (@precioarts==nil) %>
    <% if @listaprecio.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@listaprecio.errors.count, "error") %> prohibited this precioart from being saved:</h2>

        <ul>
          <% @listaprecio.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% else %>
    <% if @precioarts.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@precioarts.errors.count, "error") %> prohibited this precioart from being saved:</h2>

        <ul>
          <% @precioarts.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>

  <div class="field">
    <%= f.label :Articulos %>
   <!-- <div class ="combobox">  <%= f.collection_select(:comercializable_id,Comercializable.all(:include => :rola ) , :id,:nombreart , {:prompt => 'Agregar un Articulo'}, :class =>  'text ui-widget-content ui-corner-all' , :id => "precioart_comercializable_id" + @rand.to_s()) %></div> -->
   <div class ="combobox"> <%= f.text_field :comercializable_id , :size =>20, :class =>  'filtro' ,:id => "comercializable_id" + @rand.to_s  ,:style=>"width: 18em !important;" ,:tabindex=>1%>
     <span id="nombre_producto<%= @rand %>" style="color: red;"><%if (@precioarts.comercializable != nil) %><%=  @precioarts.comercializable.nombreart  %> <%end;%></span>
   </div>
  </div>

  <div id="ineer_error<%= @rand %>"></div>
  <div class="field">
    <%= f.label :precio %><br />
    <div class ="combobox"> <%= f.text_field :precio , :size =>20, :class =>  'text ui-widget-content ui-corner-all', :id => "precioart_precio" + @rand.to_s()%></div>
  </div>
  <div class="field">
    <%= f.label :descuento %><br />
    <div class ="combobox"> <%= f.text_field :descuento , :size =>20, :class =>  'text ui-widget-content ui-corner-all' , :id => "precioart_descuento" + @rand.to_s()%></div>
  </div>



  <div class="actions" >
    <a id="guardar_precioart<%= @rand %>"><%if (@rand!="") %>Guardar Cambios <%else%>Crear Nuevo<%end;%> </a>
  </div>

<% end %>

app/views/precioarts/_precioart.html.erb
<tr>
    <td class="ui-state-default ui-corner-all"><% if(precioart.comercializable!=nil) %>
                                               <%=   precioart.comercializable.id %>
                                               <% end; %></td>
    <td class="ui-state-default ui-corner-all"><% if(precioart.comercializable!=nil) %>
                                               <%=   precioart.comercializable.nombreart %>
                                               <% end; %></td>
    <td class="ui-state-default ui-corner-all"><%= precioart.precio %></td>
    <td class="ui-state-default ui-corner-all"><%= precioart.descuento %></td>


    <td class="ui-state-default ui-corner-all"><a href ="#" data="/listaprecios/<%=  @listaprecio.id %>/precioarts/<%=precioart.id%>/edit" dataw="590"  datah="200" class="edit_sub_link" title="Editar promocion"><span class="ui-icon ui-icon-wrench"></span></a></td>
    <td class="ui-state-default ui-corner-all"><a href="#" action="/listaprecios/<%=  @listaprecio.id %>/precioarts/<%=precioart.id%>" class="delete_sub_list"  title="Eliminar precio articulo"><span class="ui-icon ui-icon-trash"></span></a></td>
   
</tr>

app/views/precioarts/edit.html.erb
<%= render 'form' %>

app/views/precioarts/index.html.erb
<h1>Listing precioarts</h1>

<table>
  <tr>
    <th>Precio</th>
    <th>Descuento</th>
    <th>Comercializable</th>
    <th>Listaprecio</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @precioarts.each do |precioart| %>
  <tr>
    <td><%= precioart.precio %></td>
    <td><%= precioart.descuento %></td>
    <td><%= precioart.comercializable %></td>
    <td><%= precioart.listaprecio %></td>
    <td><%= link_to 'Show', precioart %></td>
    <td><%= link_to 'Edit', edit_precioart_path(precioart) %></td>
    <td><%= link_to 'Destroy', precioart, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Precioart', new_precioart_path %>

app/views/precioarts/new.html.erb
<%= render 'form' %>

app/views/precioarts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Precio:</b>
  <%= @precioart.precio %>
</p>

<p>
  <b>Descuento:</b>
  <%= @precioart.descuento %>
</p>

<p>
  <b>Comercializable:</b>
  <%= @precioart.comercializable %>
</p>

<p>
  <b>Listaprecio:</b>
  <%= @precioart.listaprecio %>
</p>


<%= link_to 'Edit', edit_precioart_path(@precioart) %> |
<%= link_to 'Back', precioarts_path %>