config/routes.rb
Factpand3::Application.routes.draw do

  resource :reportes do
    get 'facturado', :on => :collection
    get 'movimientos', :on => :collection
    get 'articulos_reporte', :on => :collection
    get 'conjunto_articulos_reporte', :on => :collection
  end

  resources :notadedebitos do
    resources :renglon_notadebitos
    resources :renglon_ndddetalles
    resources :renglon_nddndcs
    resources :renglon_ndd_articulos
    get 'filtered' , :on => :collection
    get 'proximo_preimpreso', :on => :collection
    get 'generar_impresion' , :on => :collection
    get 'anular', :on => :collection
  end

  resources :notadecreditos do
    resources :renglon_notacreditos
    resources :renglon_ndcdetalles
    resources :renglon_ndcndds
    resources :renglon_ndc_articulos
    get 'filtered' , :on => :collection
    get 'proximo_preimpreso', :on => :collection
    get 'generar_impresion' , :on => :collection
    get 'anular', :on => :collection
  end

  resource :sessions, :only => [ :new, :create, :destroy]

  match '/signin', :to => 'sessions#new'

  match '/signout', :to => 'sessions#destroy'

  match '/signup', :to => 'users#new'

  resources :users

  resources :recibos do
    resources :renglon_recibos
    resources :renglon_recdetalles
    resources :renglon_recibo_docs
    get 'filtered' , :on => :collection
    get 'proximo_preimpreso', :on => :collection
    get 'generar_impresion' , :on => :collection
    get 'anular', :on => :collection
  end

  resources :facturas do
    get 'proximo_preimpreso', :on => :collection
    get 'filtered' , :on => :collection
    get 'generar_impresion' , :on => :collection
    get 'anular', :on => :collection
    resources :renglon_facturas
    resources :renglon_factdetalles
  end

  resources :listaprecios do
    get 'getPrecioArticuloCliente', :on => :collection
     get 'importarcliente', :on => :collection
    get 'copiarlista', :on => :collection
    resources :precioarts
  end

  root :to => "page#home"

  resources :articulocomps do
    resources :rolarticulos
    resources :comercializables do
      resources :precioarts
    end
  end

  resources :articuloinds do
    resources :rolarticulos
    resources :comercializables do
      resources :precioarts
    end
  end

  resources :tipoclientes do
    resources :mail_internos
  end

  resources :impuestos

  resources :pagocontados

  resources :pagoacreditos

  resources :monedas

  resources :formadepagos

  resources :articulos do
    resources :rolarticulos
    resources :comercializables do
      resources :precioarts
    end    
  end

  resources :promocions

  resources :sucursals

  resources :empresas do
    resources :contactos do
       resources :telefonos
       resources :mail_internos
    end
    resources :descuento_clientes
    resources :telefonos
    resources :mail_internos
    resources :sucursals do
      resources :telefonos
      resources :mail_internos
      resources :contactos do
        resources :telefonos
        resources :mail_internos
      end
    end
  end
  
  resources :sucursals do
    resources :telefonos
    resources :mail_internos
    resources :contactos do
      resources :telefonos
      resources :mail_internos
    end
  end

  resources :contactos do
    resources :telefonos
    resources :mail_internos
  end

  resources :clientes do
    resources :descuento_clientes
  end

  resources :personas do
    resources :telefonos
    resources :mail_internos
    resources :descuento_clientes
  end

end

app/models/renglon_factdetalle.rb
# == Schema Information
#
# Table name: renglon_factdetalles
#
#  id              :integer          not null, primary key
#  factura_id      :integer          not null
#  detalle         :string(255)      not null
#  total_renglon   :float            not null
#  total_impuestos :float            not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class RenglonFactdetalle < ActiveRecord::Base

  belongs_to :factura

  has_many :impuestos_renglon_factdetalle
  has_many :impuestos, :through => :impuestos_renglon_factdetalle
  has_many :foto_impuesto_facts, :as => :renglon, :dependent => :destroy

  private

  validate :factura_impresa
  validates_numericality_of :total_impuestos, :message => "El caracter de separacion decimal es .(Punto)."
  validates_numericality_of :total_renglon, :message => "El caracter de separacion decimal es .(Punto)."


  before_destroy :factura_val?

  def factura_val?
    errors.add(:factura, "No puede modificar una Facura impresa.") if self.factura.impresa?
    errors.blank?
  end

  def factura_impresa
    errors.add(:factura,"No puede modificar una Facura impresa.") if self.factura.impresa?
  end

end

app/controllers/renglon_factdetalles_controller.rb
class RenglonFactdetallesController < ApplicationController

  before_filter :authenticate

  # GET /renglon_factdetalles
  # GET /renglon_factdetalles.json
  def index
    @factura = Factura.find(params[:factura_id])
    @renglon_factdetalles = @factura.renglon_factdetalles.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @renglon_factdetalles }
    end
  end

  # GET /renglon_factdetalles/1
  # GET /renglon_factdetalles/1.json
  def show
    @factura = Factura.find(params[:factura_id])
    @renglon_factdetalle = @factura.renglon_factdetalles.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @renglon_factdetalle }
    end
  end

  # GET /renglon_factdetalles/new
  # GET /renglon_factdetalles/new.json
  def new
    @renglon_factdetalle = RenglonFactdetalle.new

    respond_to do |format|
       format.html { render :layout => 'special_form'}# new.html.erb
      format.json { render json: @renglon_factdetalle }
    end
  end

  # GET /renglon_factdetalles/1/edit
  def edit
    @factura = Factura.find(params[:factura_id])
    @renglon_factdetalle = @factura.renglon_factdetalles.find(params[:id])
     respond_to do |format|
      format.html { render :layout => 'special_form'}# new.html.erb
       format.json { render json: @renglon_factdetalle }
    end
  end

  # POST /renglon_factdetalles
  # POST /renglon_factdetalles.json
  def create
    @factura = Factura.find(params[:factura_id])
    @renglon_factdetalle = RenglonFactdetalle.new(params[:renglon_factdetalle])
    @factura.renglon_factdetalles << @renglon_factdetalle

    respond_to do |format|
      if @factura.save
        format.html { redirect_to @factura, notice: 'Renglon factdetalle was successfully created.' }
        format.json { render json: @renglon_factdetalle}
      else
        format.html { render action: "new" }
        format.json { render json: @renglon_factdetalle.errors }
      end
    end
  end

  # PUT /renglon_factdetalles/1
  # PUT /renglon_factdetalles/1.json
  def update
    @factura = Factura.find(params[:factura_id])
    @renglon_factdetalle = @factura.renglon_factdetalles.find(params[:id])

    if (params[:renglon_factdetalle][:impuesto_ids] == nil)
      params[:renglon_factdetalle][:impuesto_ids] = []
    end

    respond_to do |format|
      if @renglon_factdetalle.update_attributes(params[:renglon_factdetalle])
        format.html { redirect_to @factura, notice: 'Renglon factdetalle was successfully updated.' }
        format.json { render json: @renglon_factdetalle }
      else
        format.html { render action: "edit" }
        format.json { render json: @renglon_factdetalle.errors }
      end
    end
  end

  # DELETE /renglon_factdetalles/1
  # DELETE /renglon_factdetalles/1.json
  def destroy
    @factura = Factura.find(params[:factura_id])
    @renglon_factdetalle = @factura.renglon_factdetalles.find(params[:id]).destroy

    respond_to do |format|
      format.html { head :ok }
      format.json { head :ok }
    end
  end
end

app/helpers/renglon_factdetalles_helper.rb
module RenglonFactdetallesHelper
end

app/views/renglon_factdetalles/_form.html.erb
<script>
  var impuestos = [];
<%

@impuestos =   Impuesto.all()
@impuestos.each{|index| %>
    impuestos[<%=   index.id %>] = <%=   index.porcentajea %>;
<%
}
%>
  $(function() {
    <% @rand =  (0...8).map{65.+(rand(25)).chr}.join   %>
    <% if(@renglon_factdetalle != nil) %>

      <%  @rand = @renglon_factdetalle.id %>
    <% end; %>

    $( "#renglon_factdetalle_detalle<%= @rand %>" ).focus();

    $( "#renglon_factdetalle_total_renglon<%= @rand %>" ).keypress(function(e){
       if(e.keyCode == 13){
           $( "#guardar_renglon_detalle<%= @rand %>" ).click();
       }
    });

    $(".impuesto").change(function(){
      var valor_original = 0;
      var valor = $("#renglon_factdetalle_total_renglon<%= @rand %>").val();
      $(".impuesto:checked").each(function(){

        valor_original = valor_original + (impuestos[$(this).attr("data")])/100;

      });
      $( "#renglon_factdetalle_total_impuestos<%= @rand %>" ).val(reondeo(($( "#renglon_factdetalle_total_renglon<%= @rand %>" ).val())*(1/(1+valor_original))*valor_original));
  
    });


    $( "#renglon_factdetalle_total_renglon<%= @rand %>" ).keyup(function(){
      var valor_original =0;
      var valor = $(this).val();
      $(".impuesto:checked").each(function(){

        valor_original = valor_original  + (impuestos[$(this).attr("data")])/100;

      });
      $( "#renglon_factdetalle_total_impuestos<%= @rand %>" ).val(reondeo(($( "#renglon_factdetalle_total_renglon<%= @rand %>" ).val())*(1/(1+valor_original))*valor_original));
    });

    $( "#guardar_renglon_detalle<%= @rand %>" ).button();
    $( "#guardar_renglon_detalle<%= @rand %>" ).click(function() {
      $( "#guardar_renglon_detalle<%= @rand %>" ).button( "disable" );
      var impuesto_ids = new Array();
      $(".impuesto:checked").each(function(){

        impuesto_ids.push(parseInt($(this).attr("data")));

      });
  

      
      var data = new Object();
<% if(@renglon_factdetalle != nil) %>
        data["_method"] =	"put";

<% end; %>
      data['renglon_factdetalle[detalle]'] =	$( "#renglon_factdetalle_detalle<%= @rand %>" ).val();
      data['renglon_factdetalle[total_impuestos]'] =	$( "#renglon_factdetalle_total_impuestos<%= @rand %>" ).val();
      data['renglon_factdetalle[total_renglon]'] =	$( "#renglon_factdetalle_total_renglon<%= @rand %>" ).val() - $( "#renglon_factdetalle_total_impuestos<%= @rand %>" ).val();
      data['renglon_factdetalle[impuesto_ids][]'] =	impuesto_ids;


      data['commit'] = "Create factura"
      data["utf8"] =	true;
      $.ajax({
        type: "POST",
        url: "/facturas/<%= @factura.id %>/renglon_factdetalles<% if (@renglon_factdetalle==nil) %>.json/ <% else %>/<%= @renglon_factdetalle.id %>.json <%end%>",
        data: data,
        context: document.body,
        success: function(json_data){
          $( "#guardar_renglon_detalle<%= @rand %>" ).button( "enable" );
          if (json_data.id){
            $("#texto_error<%= @rand %>").html("");
          
            <% if (@renglon_factdetalle!=nil) %>
              closeIframe("/facturas/<%= @factura.id %>/renglon_factdetalles/<%= @renglon_factdetalle.id %>/edit");
            <%end%>
          
            reloadIframe("/facturas/<%=@factura.id %>/edit",1)
          }else{
            $("#texto_error_inner<%= @rand %>").html("");
            for (var i in json_data){
              var error = '<div style="padding: 0 .2em;" class="ui-state-error ui-corner-all"><p><span style="float: left; margin-right: .3em;" class="ui-icon ui-icon-alert"></span><strong>'+i+':</strong> '+json_data[i]+'.</p></div><br/>';
              $("#texto_error_inner<%= @rand %>").html($("#texto_error_inner<%= @rand %>").html()+error);

            }
          }
        },
        error: function( xhr, status, index, anchor ) {
          $( "#guardar_renglon_detalle<%= @rand %>" ).button( "enable" )
          $("#texto_error_inner<%= @rand %>").html("");
          for (var i in xhr){
            var error = '<div style="padding: 0 .2em;" class="ui-state-error ui-corner-all"><p><span style="float: left; margin-right: .3em;" class="ui-icon ui-icon-alert"></span><strong>'+i+':</strong> '+xhr[i]+'.</p></div><br/>';
            $("#texto_error_inner<%= @rand %>").html($("#texto_error_inner<%= @rand %>").html()+error);

          }
        }
      });
      return false;
    });
  });

</script>
<style>
  #impuesto{
    width: auto;
    height: 120px;
    border: 1px #5c5c5c solid;
    padding: 0px;
    overflow: auto;
    margin-bottom: 15px;
  }
  #impuesto input{
    margin-left: 150px;
  }
  #impuesto div{
    border: 1px #5c5c5c solid;
    background-color: #0b93d5;
    padding: 4px 0 4px 10px;
    margin: 0px;
  }

  #impuesto label{
    padding-left: 10px;
  }
</style>
<% if  (@renglon_factdetalle==nil) %>
  <% @renglon_factdetalle = RenglonFactdetalle.new %>
<% end %>

<%= form_for([@factura,@renglon_factdetalle]) do |f| %>
  <% if @factura.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@factura.errors.count, "error") %> prohibited this renglon_factura from being saved:</h2>

      <ul>
        <% @factura.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div id="texto_error_inner<%= @rand %>"> </div>
  <div class="field">
    <%= f.label :detalle %>
    <div class ="combobox"> <%= f.text_field :detalle , :size =>48, :class =>  'text ui-widget-content ui-corner-all', :tabindex=>1, :id => "renglon_factdetalle_detalle" + @rand.to_s%></div>
  </div>

  <div class="field" id="impuesto">
    <div>
      <%= f.label :impuestos %>
    </div>

    <% if @renglon_factdetalle.id == nil %>
      <% for imp in Impuesto.all() %>
        <%= label_tag "renglon_factdetalle[impuesto_ids][]", imp.nombre , :for => "renglon_factdetalle[impuesto_id][]" %>
        <%= check_box_tag "renglon_factdetalle[impuesto_ids][]", imp.id ,false , :class => "impuesto",:data => imp.id %><br/>

      <% end %>
    <% else %>
      <% for imp in Impuesto.all() %>
        <%= label_tag "renglon_factdetalle[impuesto_ids][]", imp.nombre , :for => "renglon_factdetalle[impuesto_id][]" %>
        <%= check_box_tag "renglon_factdetalle[impuesto_ids][]", imp.id ,@renglon_factdetalle.impuestos.include?(imp) , :class => "impuesto",:data => imp.id %><br/>
      <% end %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :total_renglon %>
    <div class ="combobox">  <%= f.text_field :total_renglon , :size =>20, :class =>  'text ui-widget-content ui-corner-all', :tabindex=>2, :id => "renglon_factdetalle_total_renglon" + @rand.to_s%></div>
  </div>

  <div class="field">
    <%= f.label :total_impuestos %>
    <div class ="combobox">  <%= f.text_field :total_impuestos , :size =>20, :class =>  'text ui-widget-content ui-corner-all',:id => "renglon_factdetalle_total_impuestos" + @rand.to_s,:readonly=>"readonly"%></div>
  </div>


  <div class="actions" >
    <a id="guardar_renglon_detalle<%= @rand %>"><%if (@renglon_factdetalle != nil) %>Guardar Cambios <%else%>Crear Nuevo<%end;%> </a>
  </div>
<% end %>

app/views/renglon_factdetalles/_renglon_factdetalle.html.erb
<tr>
  <th class="ui-state-default ui-corner-all" width="50px">  <%= renglon_factdetalle.detalle %></th>
  <th class="ui-state-default ui-corner-all" width="50px">  <%= renglon_factdetalle.total_impuestos %></th>
  <th class="ui-state-default ui-corner-all" width="50px">  <%= renglon_factdetalle.total_renglon %></th>
  <th class="ui-state-default ui-corner-all" width="50px">  <%= ((renglon_factdetalle.total_impuestos + renglon_factdetalle.total_renglon)*100).round/100.0 %></th>
  <th  class="ui-state-default ui-corner-all"><a href ="#" data="/facturas/<%=renglon_factdetalle.factura.id %>/renglon_factdetalles/<%=  renglon_factdetalle.id %>/edit" dataw="600"  datah="600" class="edit_sub_link" title="Editar Linea"><span class="ui-icon ui-icon-wrench"></span></a></th>
  <th  class="ui-state-default ui-corner-all"><a href="#" action="/facturas/<%=renglon_factdetalle.factura.id %>/renglon_factdetalles/<%=  renglon_factdetalle.id %>" class="delete_sub_list" data-method="delete" title="Eliminar Linea"><span class="ui-icon ui-icon-trash"></span></a></th>

</tr>

app/views/renglon_factdetalles/edit.html.erb
<%= render 'form' %>

app/views/renglon_factdetalles/index.html.erb
<h1>Listing renglon_factdetalles</h1>

<table>
  <tr>
    <th>Factura</th>
    <th>Detalle</th>
    <th>Subtotal linea</th>
    <th>Impuestos</th>
    <th>Total linea</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @renglon_factdetalles.each do |renglon_factdetalle| %>
  <tr>
    <td><%= renglon_factdetalle.factura_id %></td>
    <td><%= renglon_factdetalle.detalle %></td>
    <td><%= renglon_factdetalle.subtotal_linea %></td>
    <td><%= renglon_factdetalle.impuestos %></td>
    <td><%= renglon_factdetalle.total_linea %></td>
    <td><%= link_to 'Show', renglon_factdetalle %></td>
    <td><%= link_to 'Edit', edit_renglon_factdetalle_path(renglon_factdetalle) %></td>
    <td><%= link_to 'Destroy', renglon_factdetalle, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Renglon factdetalle', new_renglon_factdetalle_path %>

app/views/renglon_factdetalles/new.html.erb
<h1>New renglon_factdetalle</h1>

<%= render 'form' %>

<%= link_to 'Back', renglon_factdetalles_path %>

app/views/renglon_factdetalles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Factura:</b>
  <%= @renglon_factdetalle.factura_id %>
</p>

<p>
  <b>Detalle:</b>
  <%= @renglon_factdetalle.detalle %>
</p>

<p>
  <b>Subtotal linea:</b>
  <%= @renglon_factdetalle.subtotal_linea %>
</p>

<p>
  <b>Impuestos:</b>
  <%= @renglon_factdetalle.impuestos %>
</p>

<p>
  <b>Total linea:</b>
  <%= @renglon_factdetalle.total_linea %>
</p>


<%= link_to 'Edit', edit_renglon_factdetalle_path(@renglon_factdetalle) %> |
<%= link_to 'Back', renglon_factdetalles_path %>