config/routes.rb
Factpand3::Application.routes.draw do

  resource :reportes do
    get 'facturado', :on => :collection
    get 'movimientos', :on => :collection
    get 'articulos_reporte', :on => :collection
    get 'conjunto_articulos_reporte', :on => :collection
  end

  resources :notadedebitos do
    resources :renglon_notadebitos
    resources :renglon_ndddetalles
    resources :renglon_nddndcs
    resources :renglon_ndd_articulos
    get 'filtered' , :on => :collection
    get 'proximo_preimpreso', :on => :collection
    get 'generar_impresion' , :on => :collection
    get 'anular', :on => :collection
  end

  resources :notadecreditos do
    resources :renglon_notacreditos
    resources :renglon_ndcdetalles
    resources :renglon_ndcndds
    resources :renglon_ndc_articulos
    get 'filtered' , :on => :collection
    get 'proximo_preimpreso', :on => :collection
    get 'generar_impresion' , :on => :collection
    get 'anular', :on => :collection
  end

  resource :sessions, :only => [ :new, :create, :destroy]

  match '/signin', :to => 'sessions#new'

  match '/signout', :to => 'sessions#destroy'

  match '/signup', :to => 'users#new'

  resources :users

  resources :recibos do
    resources :renglon_recibos
    resources :renglon_recdetalles
    resources :renglon_recibo_docs
    get 'filtered' , :on => :collection
    get 'proximo_preimpreso', :on => :collection
    get 'generar_impresion' , :on => :collection
    get 'anular', :on => :collection
  end

  resources :facturas do
    get 'proximo_preimpreso', :on => :collection
    get 'filtered' , :on => :collection
    get 'generar_impresion' , :on => :collection
    get 'anular', :on => :collection
    resources :renglon_facturas
    resources :renglon_factdetalles
  end

  resources :listaprecios do
    get 'getPrecioArticuloCliente', :on => :collection
     get 'importarcliente', :on => :collection
    get 'copiarlista', :on => :collection
    resources :precioarts
  end

  root :to => "page#home"

  resources :articulocomps do
    resources :rolarticulos
    resources :comercializables do
      resources :precioarts
    end
  end

  resources :articuloinds do
    resources :rolarticulos
    resources :comercializables do
      resources :precioarts
    end
  end

  resources :tipoclientes do
    resources :mail_internos
  end

  resources :impuestos

  resources :pagocontados

  resources :pagoacreditos

  resources :monedas

  resources :formadepagos

  resources :articulos do
    resources :rolarticulos
    resources :comercializables do
      resources :precioarts
    end    
  end

  resources :promocions

  resources :sucursals

  resources :empresas do
    resources :contactos do
       resources :telefonos
       resources :mail_internos
    end
    resources :descuento_clientes
    resources :telefonos
    resources :mail_internos
    resources :sucursals do
      resources :telefonos
      resources :mail_internos
      resources :contactos do
        resources :telefonos
        resources :mail_internos
      end
    end
  end
  
  resources :sucursals do
    resources :telefonos
    resources :mail_internos
    resources :contactos do
      resources :telefonos
      resources :mail_internos
    end
  end

  resources :contactos do
    resources :telefonos
    resources :mail_internos
  end

  resources :clientes do
    resources :descuento_clientes
  end

  resources :personas do
    resources :telefonos
    resources :mail_internos
    resources :descuento_clientes
  end

end

app/models/renglon_ndddetalle.rb
# == Schema Information
#
# Table name: renglon_ndddetalles
#
#  id              :integer          not null, primary key
#  detalle         :string(255)      not null
#  notadedebito_id :integer          not null
#  total_impuestos :float            not null
#  total_renglon   :float            not null
#  factura_id      :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class RenglonNdddetalle < ActiveRecord::Base
  belongs_to :notadedebito
  belongs_to :factura
  has_many :impuestos_renglon_ndd, :as => :renglon
  has_many :impuestos, :through => :impuestos_renglon_ndd
  has_many :foto_impuesto_ndds, :as => :renglon, :dependent => :destroy


  private

  validate :notadedebito_impresa
  validates_numericality_of :total_impuestos, :message => "El caracter de separacion decimal es .(Punto)."
  validates_numericality_of :total_renglon, :message => "El caracter de separacion decimal es .(Punto)."



  after_update :actualizar_impuestos

  before_destroy :notadedebito_val?


  def notadedebito_val?
    errors.add(:notadedebito, "No puede modificar una Nota de Debito impresa.") if self.notadedebito.impresa?
    errors.blank?
  end

  def actualizar_impuestos
    for im in self.foto_impuesto_ndds
      im.destroy
    end
    for imp in self.impuestos
      @fi = self.foto_impuesto_ndds.create(:nombre => imp.nombre, :porcentaje => imp.porcentajea)
      @fi.save
    end

  end


  def notadedebito_impresa
    errors.add(:notadedebito,"No puede modificar una Nota de Debito impresa.") if self.notadedebito.impresa?
  end

end

app/controllers/renglon_ndddetalles_controller.rb
class RenglonNdddetallesController < ApplicationController


  before_filter :authenticate


  # GET /renglon_ndddetalles
  # GET /renglon_ndddetalles.json
  def index
    @notadedebito = Notadedebito.find(params[:notadedebito_id])
    @renglon_ndddetalles = @notadedebito.renglon_ndddetalles

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @renglon_ndddetalles }
    end
  end

  # GET /renglon_ndddetalles/1
  # GET /renglon_ndddetalles/1.json
  def show
    @notadedebito = Notadedebito.find(params[:notadedebito_id])
    @renglon_ndddetalles = @notadedebito.renglon_ndddetalles.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @renglon_ndddetalle }
    end
  end

  # GET /renglon_ndddetalles/new
  # GET /renglon_ndddetalles/new.json
  def new
    @renglon_ndddetalle = RenglonNdddetalle.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @renglon_ndddetalle }
    end
  end

  # GET /renglon_ndddetalles/1/edit
  def edit
    @notadedebito = Notadedebito.find(params[:notadedebito_id])
    @renglon_ndddetalles = @notadedebito.renglon_ndddetalles.find(params[:id])
    respond_to do |format|
      format.html { render json: @renglon_ndddetalles}# new.html.erb
    end
  end

  # POST /renglon_ndddetalles
  # POST /renglon_ndddetalles.json
  def create

    @notadedebito = Notadedebito.find(params[:notadedebito_id])
    @renglon_ndddetalle = @notadedebito.renglon_ndddetalles.create(params[:renglon_ndddetalle])

    respond_to do |format|
      if @renglon_ndddetalle.save
        format.html { redirect_to @notadedebito, notice: 'Renglon ndddetalle was successfully created.' }
        format.json { render json: @renglon_ndddetalle }
      else
        format.html { render action: "new" }
        format.json { render json: @renglon_ndddetalle.errors }
      end
    end
  end

  # PUT /renglon_ndddetalles/1
  # PUT /renglon_ndddetalles/1.json
  def update
    @notadedebito = Notadedebito.find(params[:notadedebito_id])
    @renglon_ndddetalles = @notadedebito.renglon_ndddetalles.find(params[:id])

    respond_to do |format|
      if @renglon_ndddetalle.update_attributes(params[:renglon_ndddetalle])
        format.html { redirect_to @renglon_ndddetalle, notice: 'Renglon ndddetalle was successfully updated.' }
        format.json {  render json: @renglon_ndddetalle }
      else
        format.html { render action: "edit" }
        format.json { render json: @renglon_ndddetalle.errors }
      end
    end
  end

  # DELETE /renglon_ndddetalles/1
  # DELETE /renglon_ndddetalles/1.json
  def destroy

    @notadedebito = Notadedebito.find(params[:notadedebito_id])
    @renglon_ndddetalles = @notadedebito.renglon_ndddetalles.find(params[:id]).destroy

    respond_to do |format|
      format.html { redirect_to notadedebito_url }
      format.json { head :ok }
    end
  end
end

app/helpers/renglon_ndddetalles_helper.rb
module RenglonNdddetallesHelper
end

app/views/renglon_ndddetalles/_form.html.erb
<script>
  var impuestos = [];
<%

@impuestos =   Impuesto.all()
@impuestos.each{|index| %>
    impuestos[<%=   index.id %>] = <%=   index.porcentajea %>;
<%
}
%>
  $(function() {
<% @rand =  (0...8).map{65.+(rand(25)).chr}.join   %>

    $(".impuesto").change(function(){
        var valor_original = 0;
        $(".impuesto:checked").each(function(){

          valor_original = valor_original + (impuestos[$(this).attr("data")])/100;

        });
        $( "#renglon_ndddetalle_total_impuestos<%= @rand %>" ).val(reondeo($( "#renglon_ndddetalle_total_renglon<%= @rand %>" ).val()*(1/(1+valor_original))*valor_original));

    });


    $( "#renglon_ndddetalle_total_renglon<%= @rand %>" ).keyup(function(){
      var valor_original = 0;
      var valor = $(this).val();
      $(".impuesto:checked").each(function(){

        valor_original = valor_original + (impuestos[$(this).attr("data")])/100;

      });
      $( "#renglon_ndddetalle_total_impuestos<%= @rand %>" ).val(reondeo($( "#renglon_ndddetalle_total_renglon<%= @rand %>" ).val()*(1/(1+valor_original))*valor_original));
    });

    $( "#guardar_renglon_ndddetalle<%= @rand %>" ).button();
    $( "#guardar_renglon_ndddetalle<%= @rand %>" ).click(function() {
      $( "#guardar_renglon_ndddetalle<%= @rand %>" ).button( "disable" );
      var impuesto_ids = new Array();
      $(".impuesto:checked").each(function(){

        impuesto_ids.push(parseInt($(this).attr("data")));

      });



      var data = new Object();
    <% if(@renglon_ndddetalle != nil) %>
        data["_method"] =	"put";

    <% end; %>
      data['renglon_ndddetalle[detalle]'] =	$( "#renglon_ndddetalle_detalle<%= @rand %>" ).val();
      data['renglon_ndddetalle[total_impuestos]'] =	$( "#renglon_ndddetalle_total_impuestos<%= @rand %>" ).val();
      data['renglon_ndddetalle[total_renglon]'] =	$( "#renglon_ndddetalle_total_renglon<%= @rand %>" ).val() - $( "#renglon_ndddetalle_total_impuestos<%= @rand %>" ).val();
      data['renglon_ndddetalle[impuesto_ids][]'] =	impuesto_ids;


      data['commit'] = "Create Nota de Debito"
      data["utf8"] =	true;
      $.ajax({
        type: "POST",
        url: "/notadedebitos/<%= @notadedebito.id %>/renglon_ndddetalles<% if (@renglon_ndddetalle==nil) %>.json/ <% else %>/<%= @renglon_ndddetalle.id %>.json <%end%>",
        data: data,
        context: document.body,
        success: function(json_data){
          $( "#guardar_renglon_ndddetalle<%= @rand %>" ).button( "enable" )
          if (json_data.id){
            $("#texto_error<%= @rand %>").html("");
              tab_selected.click();
  <% if (@renglon_ndddetalle != nil) %>
      closeIframe("/notadedebitos/<%= @notadedebito.id %>/renglon_ndddetalles/<%= @renglon_ndddetalle.id %>/edit");
  <% end %>
            reloadIframe("/notadedebitos/<%=@notadedebito.id%>/edit","Editar Nota de Debito.",900,600)
          }else{
            $("#texto_error_inner<%= @rand %>").html("");
            for (var i in json_data){
              var error = '<div style="padding: 0 .2em;" class="ui-state-error ui-corner-all"><p><span style="float: left; margin-right: .3em;" class="ui-icon ui-icon-alert"></span><strong>'+i+':</strong> '+json_data[i]+'.</p></div><br/>';
              $("#texto_error_inner<%= @rand %>").html($("#texto_error_inner<%= @rand %>").html()+error);

            }
          }
        },
        error: function( xhr, status, index, anchor ) {
          $( "#guardar_renglon_ndddetalle<%= @rand %>" ).button( "enable" )
          $("#texto_error_inner<%= @rand %>").html("");
          
            var error = '<div style="padding: 0 .2em;" class="ui-state-error ui-corner-all"><p><span style="float: left; margin-right: .3em;" class="ui-icon ui-icon-alert"></span><strong>0:</strong> Error interno.</p></div><br/>';
            $("#texto_error_inner<%= @rand %>").html($("#texto_error_inner<%= @rand %>").html()+error);

          
        }
      });
      return false;
    });
  });

</script>
<style>
  #impuesto{
    width: auto;
    height: 120px;
    border: 1px #5c5c5c solid;
    padding: 0px;
    overflow: auto;
    margin-bottom: 15px;
  }
  #impuesto input{
    margin-left: 150px;
  }
  #impuesto div{
    border: 1px #5c5c5c solid;
    background-color: #0b93d5;
    padding: 4px 0 4px 10px;
    margin: 0px;
  }

  #impuesto label{
    padding-left: 10px;
  }
</style>
<% if  (@renglon_ndddetalle==nil) %>
  <% @renglon_ndddetalle = RenglonNdddetalle.new %>
<% end %>

<%= form_for([@notadedebito,@renglon_ndddetalle]) do |f| %>
  <% if @notadedebito.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notadedebito.errors.count, "error") %> prohibited this renglon_factura from being saved:</h2>

      <ul>
        <% @notadedebito.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div id="texto_error_inner<%= @rand %>"> </div>
  <div class="field">
    <%= f.label :detalle %>
    <div class ="combobox"> <%= f.text_field :detalle , :size =>48, :class =>  'text ui-widget-content ui-corner-all',:id => "renglon_ndddetalle_detalle" + @rand.to_s%></div>
  </div>

  <div class="field" id="impuesto">
    <div>
      <%= f.label :impuestos %>
    </div>

    <% if @renglon_ndddetalle.id == nil %>
      <% for imp in Impuesto.all() %>
        <%= label_tag "renglon_ndddetalle[impuesto_ids][]", imp.nombre , :for => "renglon_ndddetalle[impuesto_id][]" %>
        <%= check_box_tag "renglon_ndddetalle[impuesto_ids][]", imp.id ,false , :class => "impuesto",:data => imp.id %><br/>

      <% end %>
    <% else %>
      <% for imp in Impuesto.all() %>
        <%= label_tag "renglon_ndddetalle[impuesto_ids][]", imp.nombre , :for => "renglon_ndddetalle[impuesto_id][]" %>
        <%= check_box_tag "renglon_ndddetalle[impuesto_ids][]", imp.id ,@renglon_ndddetalle.impuestos.include?(imp) , :class => "impuesto",:data => imp.id %><br/>
      <% end %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :total_renglon %>
    <div class ="combobox">  <%= f.text_field :total_renglon , :size =>20, :class =>  'text ui-widget-content ui-corner-all',:id => "renglon_ndddetalle_total_renglon" + @rand.to_s%></div>
  </div>

  <div class="field">
    <%= f.label :total_impuestos %>
    <div class ="combobox">  <%= f.text_field :total_impuestos , :size =>20, :class =>  'text ui-widget-content ui-corner-all',:id => "renglon_ndddetalle_total_impuestos" + @rand.to_s,:readonly=>"readonly"%></div>
  </div>


  <div class="actions" >
    <a id="guardar_renglon_ndddetalle<%= @rand %>"><%if (@renglon_ndddetalle != nil) %>Guardar Cambios <%else%>Crear Nuevo<%end;%> </a>
  </div>
<% end %>

app/views/renglon_ndddetalles/_renglon_ndddetalle.html.erb
<tr>
  <th class="ui-state-default ui-corner-all" width="50px">  <%= renglon_ndddetalle.detalle %></th>
  <th class="ui-state-default ui-corner-all" width="50px">  <%= renglon_ndddetalle.total_impuestos %></th>
  <th class="ui-state-default ui-corner-all" width="50px">  <%= renglon_ndddetalle.total_renglon %></th>
  <th class="ui-state-default ui-corner-all" width="50px">  <%= ((renglon_ndddetalle.total_impuestos + renglon_ndddetalle.total_renglon)*100).round/100.0 %></th>
  <th  class="ui-state-default ui-corner-all"><a href ="#" data="/notadedebitos/<%=renglon_ndddetalle.notadedebito.id%>/renglon_ndddetalles/<%=  renglon_ndddetalle.id %>/edit" dataw="600"  datah="600" class="edit_sub_link" title="Editar Linea"><span class="ui-icon ui-icon-wrench"></span></a></th>
  <th  class="ui-state-default ui-corner-all"><a href="#" action="/notadedebitos/<%=renglon_ndddetalle.notadedebito.id%>/renglon_ndddetalles/<%=  renglon_ndddetalle.id %>" class="delete_sub_list" data-method="delete" title="Eliminar Linea"><span class="ui-icon ui-icon-trash"></span></a></th>

</tr>

app/views/renglon_ndddetalles/edit.html.erb
<%= render 'form' %>

app/views/renglon_ndddetalles/index.html.erb
<h1>Listing renglon_ndddetalles</h1>

<table>
  <tr>
    <th>Detalle</th>
    <th>Notadedebito</th>
    <th>Total impuestos</th>
    <th>Total renglon</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @renglon_ndddetalles.each do |renglon_ndddetalle| %>
  <tr>
    <td><%= renglon_ndddetalle.detalle %></td>
    <td><%= renglon_ndddetalle.notadedebito %></td>
    <td><%= renglon_ndddetalle.total_impuestos %></td>
    <td><%= renglon_ndddetalle.total_renglon %></td>
    <td><%= link_to 'Show', renglon_ndddetalle %></td>
    <td><%= link_to 'Edit', edit_renglon_ndddetalle_path(renglon_ndddetalle) %></td>
    <td><%= link_to 'Destroy', renglon_ndddetalle, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Renglon ndddetalle', new_renglon_ndddetalle_path %>

app/views/renglon_ndddetalles/new.html.erb
<%= render 'form' %>

app/views/renglon_ndddetalles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Detalle:</b>
  <%= @renglon_ndddetalle.detalle %>
</p>

<p>
  <b>Notadedebito:</b>
  <%= @renglon_ndddetalle.notadedebito %>
</p>

<p>
  <b>Total impuestos:</b>
  <%= @renglon_ndddetalle.total_impuestos %>
</p>

<p>
  <b>Total renglon:</b>
  <%= @renglon_ndddetalle.total_renglon %>
</p>


<%= link_to 'Edit', edit_renglon_ndddetalle_path(@renglon_ndddetalle) %> |
<%= link_to 'Back', renglon_ndddetalles_path %>